model:
  base_learning_rate: 1.0e-4
  target: ldm.models.flow_matching.LatentFlowMatching
  params:
    monitor: val/loss
    latent_size: 32
    channels: 3
    mask_channels: 1

    dit_config:
      target: ldm.modules.lightning_dit.LightningDiT
      params:
        input_size: 32
        patch_size: 2
        in_channels: 4
        hidden_size: 1024
        depth: 24
        num_heads: 16
        use_rope: True
        use_qknorm: True
        use_swiglu: True
        use_rmsnorm: True

    # Frozen VQ-VAE Config
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        ckpt_path: ../../../03_model/abnormal/P2/vqvae/VQVAE-epoch=105.ckpt
        ddconfig:
          double_z: false
          z_channels: 3
          resolution: 512
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1, 2, 4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 5
    wrap: False
    train:
      target: ldm.data.kvasir.KvasirSegTrain
      params:
        size: 128
        data_csv: "/content/drive/MyDrive/01_data/data_train.txt"
        data_root: "/content/drive/MyDrive/01_data/images"
        segmentation_root: "/content/drive/MyDrive/01_data/masks"
    validation:
      target: ldm.data.kvasir.KvasirSegEval
      params:
        size: 128
        data_csv: "/content/drive/MyDrive/01_data/data_eval.txt"
        data_root: "/content/drive/MyDrive/01_data/images"
        segmentation_root: "/content/drive/MyDrive/01_data/masks"

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 1000
        max_images: 4
        increase_log_steps: False

  trainer:
    benchmark: True
    accumulate_grad_batches: 2
